version: "2.35"
services:
  flask-app:
    build: .
    ports:
    - 5001:5001
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      APP_PORT: ${APP_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
    - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_ADMIN_USER}
      POSTGRES_PASSWORD: ${DB_ADMIN_PASSWORD}
      POSTGRES_NON_ROOT_USER: ${DB_USER}
      POSTGRES_NON_ROOT_PASSWORD: ${DB_PASSWORD}
