from database import Database


def init_db(db):
    db.query("DROP TABLE IF EXISTS questions;")

    db.query('''CREATE TABLE questions (
                    qid SERIAL PRIMARY KEY,
                    question text NOT NULL,
                    answer boolean NOT NULL
                );''')
    
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The CPU is often referred to as the brain of the computer.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'HTML is a programming language.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Binary code consists of 0s and 1s.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python is a compiled language.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'RAM is volatile memory.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'HTTP stands for HyperText Transfer Protocol.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript is the same as Java.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A byte consists of 8 bits.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'CSS is used for styling web pages.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Linux is an open-source operating system.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages require a compiler.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The cloud refers to physical storage devices.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'SQL is used for database management.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'IPv6 addresses are 128 bits long.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Machine learning is a subset of artificial intelligence.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Git and GitHub are the same thing.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first computer bug was an actual insect.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'CSS stands for Cascading Style Sheets.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The Internet and the World Wide Web are the same thing.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python uses curly braces for code blocks.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A compiler translates code line by line as it executes.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript can only run in web browsers.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The motherboard connects all computer components.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'TCP/IP is the protocol suite of the Internet.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Machine code is the lowest-level programming language.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All algorithms must have a finite number of steps.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'CSS can change the content of HTML elements.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The DOM represents a document as a tree structure.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python lists are mutable.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Java is platform-independent because of the JVM.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Big O notation describes algorithm asymptotic growth rate.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A stack follows FIFO (First In First Out) principle.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'IPv4 addresses are 32 bits long.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The blockchain is a type of database.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All web browsers use the same rendering engine.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Recursion is when a function calls itself.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Assembly language is a high-level language.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The BIOS is responsible for booting the computer.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JSON stands for JavaScript Object Notation.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages are case-sensitive.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The GPU is only used for graphics processing.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'DNS translates domain names to IP addresses.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python uses dynamic typing.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All operating systems use the same file system.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A quantum bit (qubit) can be 0 and 1 simultaneously.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'AJAX can only work with XML data.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The CPU cache is faster than RAM.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Regular expressions are used for pattern matching.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All web applications require JavaScript.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A VPN encrypts your internet connection.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The term \"bit\" comes from \"binary digit\".', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'CSS Grid and Flexbox are the same technology.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All computer viruses can replicate themselves.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first programmable electronic computer was ENIAC.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'SQL injection is a type of cyber attack.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python was named after the snake.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages have garbage collection.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The Linux kernel was created by Linus Torvalds.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'HTTP is more secure than HTTPS.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'A tuple in Python is mutable.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All web pages must have a doctype declaration.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The XOR gate returns true when both inputs are true.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'CSS can create animations without JavaScript.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All sorting algorithms have the same time complexity.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first computer programmer was Ada Lovelace.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript is a single-threaded language.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All databases use SQL.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The @ symbol in CSS is used for at-rules.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python 2 and Python 3 are fully compatible.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All encryption algorithms are unbreakable.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The term \"API\" stands for Application Programming Interface.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'React is a JavaScript framework.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All computer networks use TCP/IP.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The <div> element is a block-level element.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python supports multi-inheritance.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages use the same operators.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first webpage is still online.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript is the only client-side scripting language.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All search algorithms have O(1) time complexity.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'SQL is not a turing complete programming language.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python lists can contain elements of different types.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages have built-in hash tables.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first computer mouse was made of wood.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript can manipulate the DOM.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All sorting algorithms are stable.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The <span> element is an inline element.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All Python dictionaries are unordered.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All web servers run on Linux.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first computer virus was created in the 1980s.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript has a Date object for handling dates.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages use zero-based indexing.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The <meta> tag provides metadata about the HTML document.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python has a built-in function called any().', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All computer processors have the same architecture.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The first domain name ever registered was symbolics.com.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'JavaScript can be used for server-side programming.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming problems that can be solved iteratively can be solved recursively.', true);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'The <head> section is visible on the webpage.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'Python supports function overloading.', false);")
    db.query("INSERT INTO questions VALUES (DEFAULT, 'All programming languages are Turing complete.', false);")


if __name__ == "__main__":
    with Database() as db:
        init_db(db)
