---
name: cicd

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint codebase
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_PYTHON: true
          VALIDATE_HTML: true
          VALIDATE_CSS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Check if code changed
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - "docker/**"
              - "static/**"
              - "templates/**"
              - "*.py"
              - "compose.yaml"
              - "nginx.conf"
          base: ${{ github.event.before || 'HEAD^1' }}

  run-tests:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}
    steps:
      - name: Placeholder test, currently only running status tests
        run: echo "tests passed"

  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: run-tests
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: anrayliu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          # bit of a hack, won't build if ports are empty
          export APP_PORT=1
          export DB_PORT=1
          
          docker compose build
          docker tag testmycs-app anrayliu/testmycs:app
          docker tag testmycs-dbinit anrayliu/testmycs:dbinit

      - name: Push images
        run: |
          docker push anrayliu/testmycs:app
          docker push anrayliu/testmycs:dbinit

  restart-server:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH into server and restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /server \
            && docker compose pull \
            && sudo git pull \
            && docker compose down \
            && docker compose up -d
