name: cicd

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder test
        run: echo "tests passed"

  build-and-push:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: anrayliu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          # bit of a hack, won't build if ports are empty
          export APP_PORT=1
          export DB_PORT=1
          
          docker compose build
          docker tag testmycs-app anrayliu/testmycs:app
          docker tag testmycs-dbinit anrayliu/testmycs:dbinit

      - name: Push images
        run: |
          docker push anrayliu/testmycs:app
          docker push anrayliu/testmycs:dbinit
